apiVersion: v1
kind: Pod 
metadata:
  name: ubuntu-sleeper
spec:
  serviceAccountName: dashboard-sa
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["5000"]
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]
    resources:
      requests:
        memory: "0.5Gi"
        cpu: 1
      limits:
        memory: "1Gi"
        cpu: 2
  tolerations:
  - key: app
    operator: "Equal"
    value: myapp
    effect: NoSchedule
